/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linecorp.bot.insight.model;

import java.time.Instant;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;

import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;



/**
 * GenderTile
 */

@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record GenderTile (
/**
    * users&#39; gender
    */
    
    @JsonProperty("gender")
    Gender gender,
/**
    * Percentage
    */
    
    @JsonProperty("percentage")
    Double percentage

)  {
/**
     * users&#39; gender
     */
    public enum Gender {
@JsonProperty("male")
      MALE,
    @JsonProperty("female")
      FEMALE,
    @JsonProperty("unknown")
      UNKNOWN,
    

      @JsonEnumDefaultValue
      UNDEFINED;
    }


    public static class Builder {
private Gender gender;
private Double percentage;


        public Builder() {
        }

public Builder gender(Gender gender) {
            this.gender = gender;
            return this;
        }
public Builder percentage(Double percentage) {
            this.percentage = percentage;
            return this;
        }


        public GenderTile build() {
            return new GenderTile(
gender,percentage
            );
        }
    }
}
