/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.insight.model;



import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** Daily click metrics for a single tappable area of the rich menu. */
@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record GetRichMenuInsightDailyResponseClick(
    /** Get bounds */
    @JsonProperty("bounds") GetRichMenuInsightDailyResponseBounds bounds,
    /** Per-day click metrics for the target area. */
    @JsonProperty("metrics") List<GetRichMenuInsightDailyResponseDailyMetrics> metrics) {

  public static class Builder {
    private GetRichMenuInsightDailyResponseBounds bounds;
    private List<GetRichMenuInsightDailyResponseDailyMetrics> metrics;

    public Builder(
        GetRichMenuInsightDailyResponseBounds bounds,
        List<GetRichMenuInsightDailyResponseDailyMetrics> metrics) {

      this.bounds = bounds;

      this.metrics = metrics;
    }

    public GetRichMenuInsightDailyResponseClick build() {
      return new GetRichMenuInsightDailyResponseClick(bounds, metrics);
    }
  }
}
