/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.insight.model;



import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** Daily impression and click statistics for a rich menu created via the Messaging API. */
@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record GetRichMenuInsightDailyResponse(
    /** Rich menu ID. */
    @JsonProperty("richMenuId") String richMenuId,
    /**
     * Start date (JST) of the period actually covered by the returned metrics. Format: yyyyMMdd
     * (e.g. 20260213).
     */
    @JsonProperty("metricsFrom") String metricsFrom,
    /**
     * End date (JST) of the period actually covered by the returned metrics. Format: yyyyMMdd (e.g.
     * 20260215).
     */
    @JsonProperty("metricsTo") String metricsTo,
    /** Get impression */
    @JsonProperty("impression") GetRichMenuInsightDailyResponseImpression impression,
    /** Daily click metrics for each tappable area of the rich menu. */
    @JsonProperty("clicks") List<GetRichMenuInsightDailyResponseClick> clicks) {

  public static class Builder {
    private String richMenuId;
    private String metricsFrom;
    private String metricsTo;
    private GetRichMenuInsightDailyResponseImpression impression;
    private List<GetRichMenuInsightDailyResponseClick> clicks;

    public Builder(String richMenuId) {

      this.richMenuId = richMenuId;
    }

    public Builder metricsFrom(String metricsFrom) {
      this.metricsFrom = metricsFrom;
      return this;
    }

    public Builder metricsTo(String metricsTo) {
      this.metricsTo = metricsTo;
      return this;
    }

    public Builder impression(GetRichMenuInsightDailyResponseImpression impression) {
      this.impression = impression;
      return this;
    }

    public Builder clicks(List<GetRichMenuInsightDailyResponseClick> clicks) {
      this.clicks = clicks;
      return this;
    }

    public GetRichMenuInsightDailyResponse build() {
      return new GetRichMenuInsightDailyResponse(
          richMenuId, metricsFrom, metricsTo, impression, clicks);
    }
  }
}
