/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linecorp.bot.insight.model;

import java.time.Instant;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;

import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;



/**
 * Statistics related to messages.
 * @see <a href="https://developers.line.biz/en/reference/messaging-api/#get-statistics-per-unit-response"> Documentation</a>
 */

@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record GetStatisticsPerUnitResponseOverview (
/**
    * Number of users who opened the message, meaning they displayed at least 1 bubble.
    */
    
    @JsonProperty("uniqueImpression")
    Long uniqueImpression,
/**
    * Number of users who opened any URL in the message.
    */
    
    @JsonProperty("uniqueClick")
    Long uniqueClick,
/**
    * Number of users who started playing any video or audio in the message.
    */
    
    @JsonProperty("uniqueMediaPlayed")
    Long uniqueMediaPlayed,
/**
    * Number of users who played the entirety of any video or audio in the message.
    */
    
    @JsonProperty("uniqueMediaPlayed100Percent")
    Long uniqueMediaPlayed100Percent

)  {


    public static class Builder {
private Long uniqueImpression;
private Long uniqueClick;
private Long uniqueMediaPlayed;
private Long uniqueMediaPlayed100Percent;


        public Builder() {
        }

public Builder uniqueImpression(Long uniqueImpression) {
            this.uniqueImpression = uniqueImpression;
            return this;
        }
public Builder uniqueClick(Long uniqueClick) {
            this.uniqueClick = uniqueClick;
            return this;
        }
public Builder uniqueMediaPlayed(Long uniqueMediaPlayed) {
            this.uniqueMediaPlayed = uniqueMediaPlayed;
            return this;
        }
public Builder uniqueMediaPlayed100Percent(Long uniqueMediaPlayed100Percent) {
            this.uniqueMediaPlayed100Percent = uniqueMediaPlayed100Percent;
            return this;
        }


        public GetStatisticsPerUnitResponseOverview build() {
            return new GetStatisticsPerUnitResponseOverview(
uniqueImpression,uniqueClick,uniqueMediaPlayed,uniqueMediaPlayed100Percent
            );
        }
    }
}
