/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.insight.model;



import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetStatisticsPerUnitResponseClick
 *
 * @see <a
 *     href="https://developers.line.biz/en/reference/messaging-api/#get-statistics-per-unit-response">
 *     Documentation</a>
 */
@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record GetStatisticsPerUnitResponseClick(
    /** The URL&#39;s serial number. */
    @JsonProperty("seq") Long seq,
    /** URL. */
    @JsonProperty("url") String url,
    /** Number of times the URL in the bubble was opened. */
    @JsonProperty("click") Long click,
    /** Number of users that opened the URL in the bubble. */
    @JsonProperty("uniqueClick") Long uniqueClick,
    /**
     * Number of users who opened this url through any link in the message. If another message
     * bubble contains the same URL and a user opens both links, it&#39;s counted only once.
     */
    @JsonProperty("uniqueClickOfRequest") Long uniqueClickOfRequest) {

  public static class Builder {
    private Long seq;
    private String url;
    private Long click;
    private Long uniqueClick;
    private Long uniqueClickOfRequest;

    public Builder(Long seq, String url) {

      this.seq = seq;

      this.url = url;
    }

    public Builder click(Long click) {
      this.click = click;
      return this;
    }

    public Builder uniqueClick(Long uniqueClick) {
      this.uniqueClick = uniqueClick;
      return this;
    }

    public Builder uniqueClickOfRequest(Long uniqueClickOfRequest) {
      this.uniqueClickOfRequest = uniqueClickOfRequest;
      return this;
    }

    public GetStatisticsPerUnitResponseClick build() {
      return new GetStatisticsPerUnitResponseClick(
          seq, url, click, uniqueClick, uniqueClickOfRequest);
    }
  }
}
