/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.webhook.model;



import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** Mentioned target is entire group */
@JsonTypeName("all")
@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record AllMentionee(
    /**
     * Index position of the user mention for a character in text, with the first character being at
     * position 0.
     */
    @JsonProperty("index") Integer index,
    /** The length of the text of the mentioned user. For a mention @example, 8 is the length. */
    @JsonProperty("length") Integer length)
    implements Mentionee {

  public static class Builder {
    private Integer index;
    private Integer length;

    public Builder(Integer index, Integer length) {

      this.index = index;

      this.length = length;
    }

    public AllMentionee build() {
      return new AllMentionee(index, length);
    }
  }
}
