/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linecorp.bot.webhook.model;

import java.time.Instant;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;

import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;



/**
 * BeaconContent
 */

@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record BeaconContent (
/**
    * Hardware ID of the beacon that was detected
    */
    
    @JsonProperty("hwid")
    String hwid,
/**
    * Type of beacon event.
    */
    
    @JsonProperty("type")
    Type type,
/**
    * Device message of beacon that was detected.
    */
    
    @JsonProperty("dm")
    String dm

)  {
/**
     * Type of beacon event.
     */
    public enum Type {
@JsonProperty("enter")
      ENTER,
    @JsonProperty("banner")
      BANNER,
    @JsonProperty("stay")
      STAY,
    

      @JsonEnumDefaultValue
      UNDEFINED;
    }


    public static class Builder {
private String hwid;
    
        private boolean hwid$set;
    
private Type type;
    
        private boolean type$set;
    
private String dm;
    


        public Builder() {
        }

public Builder hwid(String hwid) {
            this.hwid = hwid;
    
            this.hwid$set = true;
    
            return this;
        }
public Builder type(Type type) {
            this.type = type;
    
            this.type$set = true;
    
            return this;
        }
public Builder dm(String dm) {
            this.dm = dm;
    
            return this;
        }


        public BeaconContent build() {

            if (!this.hwid$set) {
                throw new IllegalStateException("'hwid' must be set for BeaconContent.");
            }
    

            if (!this.type$set) {
                throw new IllegalStateException("'type' must be set for BeaconContent.");
            }
    



            return new BeaconContent(
hwid,type,dm
            );
        }
    }
}
