/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.webhook.model;



import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;

/** webhook&#39;s delivery context information */
@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record DeliveryContext(
    /** Whether the webhook event is a redelivered one or not. */
    @JsonProperty("isRedelivery") Boolean isRedelivery) {

  public static class Builder {
    private Boolean isRedelivery;

    private boolean isRedelivery$set;

    public Builder() {}

    public Builder isRedelivery(Boolean isRedelivery) {
      this.isRedelivery = isRedelivery;

      this.isRedelivery$set = true;

      return this;
    }

    public DeliveryContext build() {

      if (!this.isRedelivery$set) {
        throw new IllegalStateException("'isRedelivery' must be set for DeliveryContext.");
      }

      return new DeliveryContext(isRedelivery);
    }
  }
}
