/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linecorp.bot.webhook.model;

import java.time.Instant;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;

import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;



/**
 * ImageSet
 */

@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record ImageSet (
/**
    * Image set ID. Only included when multiple images are sent simultaneously.
    */
    
    @JsonProperty("id")
    String id,
/**
    * An index starting from 1, indicating the image number in a set of images sent simultaneously. Only included when multiple images are sent simultaneously. However, it won&#39;t be included if the sender is using LINE 11.15 or earlier for Android.
    */
    
    @JsonProperty("index")
    Integer index,
/**
    * The total number of images sent simultaneously.
    */
    
    @JsonProperty("total")
    Integer total

)  {


    public static class Builder {
private String id;
private Integer index;
private Integer total;


        public Builder() {
        }

public Builder id(String id) {
            this.id = id;
            return this;
        }
public Builder index(Integer index) {
            this.index = index;
            return this;
        }
public Builder total(Integer total) {
            this.total = total;
            return this;
        }


        public ImageSet build() {
            return new ImageSet(
id,index,total
            );
        }
    }
}
