/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.webhook.model;



import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Webhook event object which contains the edited message. This event is triggered when a user edits
 * a text message. Currently, message editing is not available in one-on-one chats with LINE
 * Official Accounts, so this event is only triggered in group chats. Multiple messageEdited webhook
 * events may arrive out of order. The event with the largest timestamp represents the latest edit
 * state.
 *
 * @see <a href="https://developers.line.biz/en/reference/messaging-api/#edit-event">
 *     Documentation</a>
 */
@JsonTypeName("messageEdited")
@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record MessageEditedEvent(
    /** Get source */
    @JsonProperty("source") Source source,
    /** Time of the event in milliseconds. */
    @JsonProperty("timestamp") Long timestamp,
    /** Get mode */
    @JsonProperty("mode") EventMode mode,
    /**
     * Webhook Event ID. An ID that uniquely identifies a webhook event. This is a string in ULID
     * format.
     */
    @JsonProperty("webhookEventId") String webhookEventId,
    /** Get deliveryContext */
    @JsonProperty("deliveryContext") DeliveryContext deliveryContext,
    /** Get replyToken */
    @JsonProperty("replyToken") String replyToken,
    /** Get message */
    @JsonProperty("message") MessageContent message)
    implements Event, ReplyEvent {

  public static class Builder {
    private Source source;
    private Long timestamp;
    private EventMode mode;
    private String webhookEventId;
    private DeliveryContext deliveryContext;
    private String replyToken;
    private MessageContent message;

    public Builder(
        Long timestamp,
        EventMode mode,
        String webhookEventId,
        DeliveryContext deliveryContext,
        MessageContent message) {

      this.timestamp = timestamp;

      this.mode = mode;

      this.webhookEventId = webhookEventId;

      this.deliveryContext = deliveryContext;

      this.message = message;
    }

    public Builder source(Source source) {
      this.source = source;
      return this;
    }

    public Builder replyToken(String replyToken) {
      this.replyToken = replyToken;
      return this;
    }

    public MessageEditedEvent build() {
      return new MessageEditedEvent(
          source, timestamp, mode, webhookEventId, deliveryContext, replyToken, message);
    }
  }
}
