/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.webhook.model;


import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;

/** PostbackContent */
@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record PostbackContent(
    /** Postback data */
    @JsonProperty("data") String data,
    /** Get params */
    @JsonProperty("params") Map<String, String> params) {

  public static class Builder {
    private String data;

    private boolean data$set;

    private Map<String, String> params;

    public Builder() {}

    public Builder data(String data) {
      this.data = data;

      this.data$set = true;

      return this;
    }

    public Builder params(Map<String, String> params) {
      this.params = params;

      return this;
    }

    public PostbackContent build() {

      if (!this.data$set) {
        throw new IllegalStateException("'data' must be set for PostbackContent.");
      }

      return new PostbackContent(data, params);
    }
  }
}
