/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.messaging.model;



import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/** CouponRewardRequest */
@JsonSubTypes({
  @JsonSubTypes.Type(value = CouponCashBackRewardRequest.class, name = "cashBack"),
  @JsonSubTypes.Type(value = CouponDiscountRewardRequest.class, name = "discount"),
  @JsonSubTypes.Type(value = CouponFreeRewardRequest.class, name = "free"),
  @JsonSubTypes.Type(value = CouponGiftRewardRequest.class, name = "gift"),
  @JsonSubTypes.Type(value = CouponOthersRewardRequest.class, name = "others"),
})
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "type",
    defaultImpl = UnknownCouponRewardRequest.class,
    visible = true)
public interface CouponRewardRequest {}
