/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.messaging.model;



import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** DiscountFixedPriceInfoResponse */
@JsonTypeName("fixed")
@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record DiscountFixedPriceInfoResponse(
    /** Currency code (e.g., JPY, THB, TWD). */
    @JsonProperty("currency") Currency currency,
    /** Get fixedAmount */
    @JsonProperty("fixedAmount") Long fixedAmount)
    implements DiscountPriceInfoResponse {
  /** Currency code (e.g., JPY, THB, TWD). */
  public enum Currency {
    @JsonProperty("JPY")
    JPY,
    @JsonProperty("THB")
    THB,
    @JsonProperty("TWD")
    TWD,

    @JsonEnumDefaultValue
    UNDEFINED;
  }

  public static class Builder {
    private Currency currency;
    private Long fixedAmount;

    public Builder() {}

    public Builder currency(Currency currency) {
      this.currency = currency;
      return this;
    }

    public Builder fixedAmount(Long fixedAmount) {
      this.fixedAmount = fixedAmount;
      return this;
    }

    public DiscountFixedPriceInfoResponse build() {
      return new DiscountFixedPriceInfoResponse(currency, fixedAmount);
    }
  }
}
