/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.messaging.model;



import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** DiscountPercentagePriceInfoRequest */
@JsonTypeName("percentage")
@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record DiscountPercentagePriceInfoRequest(
    /**
     * Specifies the discount rate as a percentage. Must be an integer between 1 and 99. minimum: 1
     * maximum: 99
     */
    @JsonProperty("percentage") Integer percentage) implements DiscountPriceInfoRequest {

  public static class Builder {
    private Integer percentage;

    public Builder() {}

    public Builder percentage(Integer percentage) {
      this.percentage = percentage;
      return this;
    }

    public DiscountPercentagePriceInfoRequest build() {
      return new DiscountPercentagePriceInfoRequest(percentage);
    }
  }
}
