/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.messaging.model;



import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** FlexBubble */
@JsonTypeName("bubble")
@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record FlexBubble(
    /** Get direction */
    @JsonProperty("direction") Direction direction,
    /** Get styles */
    @JsonProperty("styles") FlexBubbleStyles styles,
    /** Get header */
    @JsonProperty("header") FlexBox header,
    /** Get hero */
    @JsonProperty("hero") FlexComponent hero,
    /** Get body */
    @JsonProperty("body") FlexBox body,
    /** Get footer */
    @JsonProperty("footer") FlexBox footer,
    /** Get size */
    @JsonProperty("size") Size size,
    /** Get action */
    @JsonProperty("action") Action action)
    implements FlexContainer {
  /** Gets or Sets direction */
  public enum Direction {
    @JsonProperty("ltr")
    LTR,
    @JsonProperty("rtl")
    RTL,

    @JsonEnumDefaultValue
    UNDEFINED;
  }

  /** Gets or Sets size */
  public enum Size {
    @JsonProperty("nano")
    NANO,
    @JsonProperty("micro")
    MICRO,
    @JsonProperty("deca")
    DECA,
    @JsonProperty("hecto")
    HECTO,
    @JsonProperty("kilo")
    KILO,
    @JsonProperty("mega")
    MEGA,
    @JsonProperty("giga")
    GIGA,

    @JsonEnumDefaultValue
    UNDEFINED;
  }

  public static class Builder {
    private Direction direction;

    private FlexBubbleStyles styles;

    private FlexBox header;

    private FlexComponent hero;

    private FlexBox body;

    private FlexBox footer;

    private Size size;

    private Action action;

    public Builder() {}

    public Builder direction(Direction direction) {
      this.direction = direction;

      return this;
    }

    public Builder styles(FlexBubbleStyles styles) {
      this.styles = styles;

      return this;
    }

    public Builder header(FlexBox header) {
      this.header = header;

      return this;
    }

    public Builder hero(FlexComponent hero) {
      this.hero = hero;

      return this;
    }

    public Builder body(FlexBox body) {
      this.body = body;

      return this;
    }

    public Builder footer(FlexBox footer) {
      this.footer = footer;

      return this;
    }

    public Builder size(Size size) {
      this.size = size;

      return this;
    }

    public Builder action(Action action) {
      this.action = action;

      return this;
    }

    public FlexBubble build() {

      return new FlexBubble(direction, styles, header, hero, body, footer, size, action);
    }
  }
}
