/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.messaging.model;



import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Width of box border. This is only for &#x60;borderWidth&#x60; in FlexBox. A value of none means
 * that borders are not rendered; the other values are listed in order of increasing width.
 */
public enum FlexBoxBorderWidth {
  @JsonProperty("none")
  NONE,

  @JsonProperty("light")
  LIGHT,

  @JsonProperty("normal")
  NORMAL,

  @JsonProperty("medium")
  MEDIUM,

  @JsonProperty("semi-bold")
  SEMI_BOLD,

  @JsonProperty("bold")
  BOLD,

  @JsonEnumDefaultValue
  UNDEFINED;

  @JsonValue
  public String toValue() {
    return switch (this) {
      case NONE -> "none";
      case LIGHT -> "light";
      case NORMAL -> "normal";
      case MEDIUM -> "medium";
      case SEMI_BOLD -> "semi-bold";
      case BOLD -> "bold";

      default -> "UNDEFINED";
    };
  }
}
