/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.messaging.model;



import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * List of users who have joined the membership
 *
 * @see <a href="https://developers.line.biz/en/reference/messaging-api/#get-membership-user-ids">
 *     Documentation</a>
 */
@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record GetJoinedMembershipUsersResponse(
    /**
     * A list of user IDs who joined the membership. Users who have not agreed to the bot user
     * agreement, are not following the bot, or are not active will be excluded. If there are no
     * users in the membership, an empty list will be returned.
     */
    @JsonProperty("userIds") List<String> userIds,
    /**
     * A continuation token to get next remaining membership user IDs. Returned only when there are
     * remaining user IDs that weren&#39;t returned in the userIds property in the previous request.
     * The continuation token expires in 24 hours (86,400 seconds).
     */
    @JsonProperty("next") String next) {

  public static class Builder {
    private List<String> userIds;
    private String next;

    public Builder(List<String> userIds) {

      this.userIds = userIds;
    }

    public Builder next(String next) {
      this.next = next;
      return this;
    }

    public GetJoinedMembershipUsersResponse build() {
      return new GetJoinedMembershipUsersResponse(userIds, next);
    }
  }
}
