/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.messaging.model;



import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.URI;

/** ImageCarouselColumn */
@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record ImageCarouselColumn(
    /** Get imageUrl */
    @JsonProperty("imageUrl") URI imageUrl,
    /** Get action */
    @JsonProperty("action") Action action) {

  public static class Builder {
    private URI imageUrl;

    private boolean imageUrl$set;

    private Action action;

    private boolean action$set;

    public Builder() {}

    public Builder imageUrl(URI imageUrl) {
      this.imageUrl = imageUrl;

      this.imageUrl$set = true;

      return this;
    }

    public Builder action(Action action) {
      this.action = action;

      this.action$set = true;

      return this;
    }

    public ImageCarouselColumn build() {

      if (!this.imageUrl$set) {
        throw new IllegalStateException("'imageUrl' must be set for ImageCarouselColumn.");
      }

      if (!this.action$set) {
        throw new IllegalStateException("'action' must be set for ImageCarouselColumn.");
      }

      return new ImageCarouselColumn(imageUrl, action);
    }
  }
}
