/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.messaging.model;



import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;

/** ImageCarouselTemplate */
@JsonTypeName("image_carousel")
@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record ImageCarouselTemplate(
    /** Get columns */
    @JsonProperty("columns") List<ImageCarouselColumn> columns) implements Template {

  public static class Builder {
    private List<ImageCarouselColumn> columns;

    private boolean columns$set;

    public Builder() {}

    public Builder columns(List<ImageCarouselColumn> columns) {
      this.columns = columns;

      this.columns$set = true;

      return this;
    }

    public ImageCarouselTemplate build() {

      if (!this.columns$set) {
        throw new IllegalStateException("'columns' must be set for ImageCarouselTemplate.");
      }

      return new ImageCarouselTemplate(columns);
    }
  }
}
