/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.messaging.model;



import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** LotteryAcquisitionConditionResponse */
@JsonTypeName("lottery")
@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record LotteryAcquisitionConditionResponse(
    /** Get lotteryProbability */
    @JsonProperty("lotteryProbability") Integer lotteryProbability,
    /** Get maxAcquireCount */
    @JsonProperty("maxAcquireCount") Integer maxAcquireCount)
    implements AcquisitionConditionResponse {

  public static class Builder {
    private Integer lotteryProbability;
    private Integer maxAcquireCount;

    public Builder() {}

    public Builder lotteryProbability(Integer lotteryProbability) {
      this.lotteryProbability = lotteryProbability;
      return this;
    }

    public Builder maxAcquireCount(Integer maxAcquireCount) {
      this.maxAcquireCount = maxAcquireCount;
      return this;
    }

    public LotteryAcquisitionConditionResponse build() {
      return new LotteryAcquisitionConditionResponse(lotteryProbability, maxAcquireCount);
    }
  }
}
