/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.messaging.model;



import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** Paginated response object containing a list of coupons. */
@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record MessagingApiPagerCouponListResponse(
    /** List of coupon summary objects. */
    @JsonProperty("items") List<CouponListResponse> items,
    /** Token for fetching the next page of results. */
    @JsonProperty("next") String next) {

  public static class Builder {
    private List<CouponListResponse> items;
    private String next;

    public Builder(List<CouponListResponse> items) {

      this.items = items;
    }

    public Builder next(String next) {
      this.next = next;
      return this;
    }

    public MessagingApiPagerCouponListResponse build() {
      return new MessagingApiPagerCouponListResponse(items, next);
    }
  }
}
