/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.messaging.model;



import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PnpTemplatedButton
 *
 * @see <a
 *     href="https://developers.line.biz/en/reference/line-notification-messages/#send-line-notification-message-template-buttons">
 *     Documentation</a>
 */
@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record PnpTemplatedButton(
    /**
     * Specify the key of the button you want to include. For available keys, see
     * https://developers.line.biz/en/docs/partner-docs/line-notification-messages/template/#buttons
     */
    @JsonProperty("buttonKey") String buttonKey,
    /** URL of the page to be opened when the user presses the button. */
    @JsonProperty("url") String url) {

  public static class Builder {
    private String buttonKey;
    private String url;

    public Builder(String buttonKey, String url) {

      this.buttonKey = buttonKey;

      this.url = url;
    }

    public PnpTemplatedButton build() {
      return new PnpTemplatedButton(buttonKey, url);
    }
  }
}
