/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.messaging.model;



import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** RichMenuRequest */
@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record RichMenuRequest(
    /** Get size */
    @JsonProperty("size") RichMenuSize size,
    /** &#x60;true&#x60; to display the rich menu by default. Otherwise, &#x60;false&#x60;. */
    @JsonProperty("selected") Boolean selected,
    /**
     * Name of the rich menu. This value can be used to help manage your rich menus and is not
     * displayed to users.
     */
    @JsonProperty("name") String name,
    /** Text displayed in the chat bar */
    @JsonProperty("chatBarText") String chatBarText,
    /** Array of area objects which define the coordinates and size of tappable areas */
    @JsonProperty("areas") List<RichMenuArea> areas) {

  public static class Builder {
    private RichMenuSize size;
    private Boolean selected;
    private String name;
    private String chatBarText;
    private List<RichMenuArea> areas;

    public Builder() {}

    public Builder size(RichMenuSize size) {
      this.size = size;
      return this;
    }

    public Builder selected(Boolean selected) {
      this.selected = selected;
      return this;
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    public Builder chatBarText(String chatBarText) {
      this.chatBarText = chatBarText;
      return this;
    }

    public Builder areas(List<RichMenuArea> areas) {
      this.areas = areas;
      return this;
    }

    public RichMenuRequest build() {
      return new RichMenuRequest(size, selected, name, chatBarText, areas);
    }
  }
}
