/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.messaging.model;



import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Replace the rich menu with the rich menu specified in the &#x60;to&#x60; property for all users
 * linked to the rich menu specified in the &#x60;from&#x60; property.
 */
@JsonTypeName("link")
@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record RichMenuBatchLinkOperation(
    /** Get from */
    @JsonProperty("from") String from,
    /** Get to */
    @JsonProperty("to") String to)
    implements RichMenuBatchOperation {

  public static class Builder {
    private String from;

    private boolean from$set;

    private String to;

    private boolean to$set;

    public Builder() {}

    public Builder from(String from) {
      this.from = from;

      this.from$set = true;

      return this;
    }

    public Builder to(String to) {
      this.to = to;

      this.to$set = true;

      return this;
    }

    public RichMenuBatchLinkOperation build() {

      if (!this.from$set) {
        throw new IllegalStateException("'from' must be set for RichMenuBatchLinkOperation.");
      }

      if (!this.to$set) {
        throw new IllegalStateException("'to' must be set for RichMenuBatchLinkOperation.");
      }

      return new RichMenuBatchLinkOperation(from, to);
    }
  }
}
