/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.messaging.model;



import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;

/** SentMessage */
@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record SentMessage(
    /** ID of the sent message. */
    @JsonProperty("id") String id,
    /**
     * Quote token of the message. Only included when a message object that can be specified as a
     * quote target was sent as a push or reply message.
     */
    @JsonProperty("quoteToken") String quoteToken) {

  public static class Builder {
    private String id;
    private String quoteToken;

    public Builder(String id) {

      this.id = id;
    }

    public Builder quoteToken(String quoteToken) {
      this.quoteToken = quoteToken;
      return this;
    }

    public SentMessage build() {
      return new SentMessage(id, quoteToken);
    }
  }
}
