/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.messaging.model;



import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

/** Gets or Sets SubscriptionPeriodDemographic */
public enum SubscriptionPeriodDemographic {
  @JsonProperty("day_7")
  DAY_7,

  @JsonProperty("day_30")
  DAY_30,

  @JsonProperty("day_90")
  DAY_90,

  @JsonProperty("day_180")
  DAY_180,

  @JsonProperty("day_365")
  DAY_365,

  @JsonEnumDefaultValue
  UNDEFINED;

  @JsonValue
  public String toValue() {
    return switch (this) {
      case DAY_7 -> "day_7";
      case DAY_30 -> "day_30";
      case DAY_90 -> "day_90";
      case DAY_180 -> "day_180";
      case DAY_365 -> "day_365";

      default -> "UNDEFINED";
    };
  }
}
