/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.messaging.model;



import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Object containing user membership subscription information. */
@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record SubscribedMembershipUser(
    /** The user&#39;s member number in the membership plan. */
    @JsonProperty("membershipNo") Integer membershipNo,
    /** UNIX timestamp at which the user subscribed to the membership. */
    @JsonProperty("joinedTime") Integer joinedTime,
    /**
     * Next payment date for membership plan. - Format: yyyy-MM-dd (e.g. 2024-02-08) - Timezone:
     * UTC+9
     */
    @JsonProperty("nextBillingDate") String nextBillingDate,
    /**
     * The period of time in months that the user has been subscribed to a membership plan. If a
     * user previously canceled and then re-subscribed to the same membership plan, only the period
     * after the re-subscription will be counted.
     */
    @JsonProperty("totalSubscriptionMonths") Integer totalSubscriptionMonths) {

  public static class Builder {
    private Integer membershipNo;
    private Integer joinedTime;
    private String nextBillingDate;
    private Integer totalSubscriptionMonths;

    public Builder(
        Integer membershipNo,
        Integer joinedTime,
        String nextBillingDate,
        Integer totalSubscriptionMonths) {

      this.membershipNo = membershipNo;

      this.joinedTime = joinedTime;

      this.nextBillingDate = nextBillingDate;

      this.totalSubscriptionMonths = totalSubscriptionMonths;
    }

    public SubscribedMembershipUser build() {
      return new SubscribedMembershipUser(
          membershipNo, joinedTime, nextBillingDate, totalSubscriptionMonths);
    }
  }
}
