/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linecorp.bot.messaging.model;

import java.time.Instant;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;

import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.net.URI;


/**
 * UserProfileResponse
 * @see <a href="https://developers.line.biz/en/reference/messaging-api/#get-profile"> Documentation</a>
 */

@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record UserProfileResponse (
/**
    * User&#39;s display name
    */
    
    @JsonProperty("displayName")
    String displayName,
/**
    * User ID
    */
    
    @JsonProperty("userId")
    String userId,
/**
    * Profile image URL. &#x60;https&#x60; image URL. Not included in the response if the user doesn&#39;t have a profile image.
    */
    
    @JsonProperty("pictureUrl")
    URI pictureUrl,
/**
    * User&#39;s status message. Not included in the response if the user doesn&#39;t have a status message.
    */
    
    @JsonProperty("statusMessage")
    String statusMessage,
/**
    * User&#39;s language, as a BCP 47 language tag. Not included in the response if the user hasn&#39;t yet consented to the LINE Privacy Policy.
    */
    
    @JsonProperty("language")
    String language

)  {


    public static class Builder {
private String displayName;
private String userId;
private URI pictureUrl;
private String statusMessage;
private String language;


        public Builder() {
        }

public Builder displayName(String displayName) {
            this.displayName = displayName;
            return this;
        }
public Builder userId(String userId) {
            this.userId = userId;
            return this;
        }
public Builder pictureUrl(URI pictureUrl) {
            this.pictureUrl = pictureUrl;
            return this;
        }
public Builder statusMessage(String statusMessage) {
            this.statusMessage = statusMessage;
            return this;
        }
public Builder language(String language) {
            this.language = language;
            return this;
        }


        public UserProfileResponse build() {
            return new UserProfileResponse(
displayName,userId,pictureUrl,statusMessage,language
            );
        }
    }
}
