<#-- @ftlvariable name="totalUsage" type="java.lang.Long" -->
<#import "__wrapper.ftlh" as wrapper>
<@wrapper.main>

    <h1>ERRRORRRR</h1>

    <div>status: ${status!"-"}</div>
    <div>error: ${error!"-"}</div>
    <div>exception: ${exception!"-"}</div>
    <div>message: ${message!"-"}</div>
    <div>errors: ${errors!"-"}</div>
    <div>trace: ${trace!"-"}</div>
    <div>path: ${path!"-"}</div>

</@wrapper.main>
