/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.audience.model;



import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

/** Audience group type */
public enum AudienceGroupType {
  @JsonProperty("UPLOAD")
  UPLOAD,

  @JsonProperty("CLICK")
  CLICK,

  @JsonProperty("IMP")
  IMP,

  @JsonProperty("CHAT_TAG")
  CHAT_TAG,

  @JsonProperty("FRIEND_PATH")
  FRIEND_PATH,

  @JsonProperty("RESERVATION")
  RESERVATION,

  @JsonProperty("APP_EVENT")
  APP_EVENT,

  @JsonProperty("VIDEO_VIEW")
  VIDEO_VIEW,

  @JsonProperty("WEBTRAFFIC")
  WEBTRAFFIC,

  @JsonProperty("IMAGE_CLICK")
  IMAGE_CLICK,

  @JsonProperty("RICHMENU_IMP")
  RICHMENU_IMP,

  @JsonProperty("RICHMENU_CLICK")
  RICHMENU_CLICK,

  @JsonProperty("POP_AD_IMP")
  POP_AD_IMP,

  @JsonProperty("TRACKINGTAG_WEBTRAFFIC")
  TRACKINGTAG_WEBTRAFFIC,

  @JsonEnumDefaultValue
  UNDEFINED;

  @JsonValue
  public String toValue() {
    return switch (this) {
      case UPLOAD -> "UPLOAD";
      case CLICK -> "CLICK";
      case IMP -> "IMP";
      case CHAT_TAG -> "CHAT_TAG";
      case FRIEND_PATH -> "FRIEND_PATH";
      case RESERVATION -> "RESERVATION";
      case APP_EVENT -> "APP_EVENT";
      case VIDEO_VIEW -> "VIDEO_VIEW";
      case WEBTRAFFIC -> "WEBTRAFFIC";
      case IMAGE_CLICK -> "IMAGE_CLICK";
      case RICHMENU_IMP -> "RICHMENU_IMP";
      case RICHMENU_CLICK -> "RICHMENU_CLICK";
      case POP_AD_IMP -> "POP_AD_IMP";
      case TRACKINGTAG_WEBTRAFFIC -> "TRACKINGTAG_WEBTRAFFIC";

      default -> "UNDEFINED";
    };
  }
}
