/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.linecorp.bot.shop.model;



import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Send mission stickers (v3)
 *
 * @see <a href="https://developers.line.biz/en/reference/partner-docs/#send-mission-stickers-v3">
 *     Documentation</a>
 */
@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record MissionStickerRequest(
    /** Destination user ID */
    @JsonProperty("to") String to,
    /** Package ID for a set of stickers */
    @JsonProperty("productId") String productId,
    /** &#x60;STICKER&#x60; */
    @JsonProperty("productType") String productType,
    /** &#x60;false&#x60; */
    @JsonProperty("sendPresentMessage") Boolean sendPresentMessage) {

  public static class Builder {
    private String to;
    private String productId;
    private String productType;
    private Boolean sendPresentMessage;

    public Builder(String to, String productId, String productType, Boolean sendPresentMessage) {

      this.to = to;

      this.productId = productId;

      this.productType = productType;

      this.sendPresentMessage = sendPresentMessage;
    }

    public MissionStickerRequest build() {
      return new MissionStickerRequest(to, productId, productType, sendPresentMessage);
    }
  }
}
