name: pom validation
on:
  push:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  test:
    name: test (JDK ${{ matrix.java }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        java: [ '17' ] # We want to test on LTSs.
    steps:
    - name: actions/setup-java@v3 (JDK ${{ matrix.java }})
      uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        architecture: x64
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        submodules: true
    - run: |
        mkdir -p ~/.gradle
        echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
    - run: python3 tests/maven-pom-validation-test.py

